server:
  port: 8001
  servlet:
    context-path: /protean


spring:
  application:
    name: protean-app-demo

  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: xxxxxxxxxx
    properties:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate:
      ddl-auto: update
      show-sql: true

  ldap:
    embedded:
      port: 8399
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
#      url: ldap://localhost:8399/

  # classpath:test-server.ldif

  datasource:
    url: jdbc:mysql://localhost:3306/demo_tables
    username: root
    password: 3frames
    driver-class-name: com.mysql.cj.jdbc.Driver




